api/urls.py
from .views import MatchApiView, UserApiView, ServerApiView, RoleApiView, HeroApiView, InviteApiView
from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'matches', MatchApiView)
router.register(r'users', UserApiView)
router.register(r'heroes', HeroApiView)
router.register(r'roles', RoleApiView)
router.register(r'servers', ServerApiView)
router.register(r'invites', InviteApiView)

urlpatterns = router.urls

authentication/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from authentication.views import LoginView, LogoutView

urlpatterns = [
    url(r'^login', LoginView.as_view(), name='login'),
    url(r'^logout', login_required(LogoutView.as_view(), login_url='/login'), name='logout')
]

invites/urls.py
from django.conf.urls import url
from .views import InviteView

urlpatterns = [
    url('', InviteView.as_view(), name='invite')
]

play/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from .views import HomeView, PlayersView

urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('social_django.urls', namespace='social')),
    url('', include(('authentication.urls', 'authentication'), namespace='auth')),
    url('home/', HomeView.as_view()),
    url('players/', PlayersView.as_view()),
    url('api/v1/', include(('api.urls', 'api'), namespace='api')),
    url('user/profile/', include(('user_profile.urls', 'user_profile'), namespace='user_profile')),
    url('user/invites/', include(('invites.urls', 'invites'), namespace='invites')),
]

invites/models.py
from django.db import models
from authentication.models import User


class Invite(models.Model):
    user_from = models.ForeignKey(User, on_delete=models.CASCADE)
    user_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='invite_to')
    time_stamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(default='Awaiting Response.', max_length=30)

invites/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class InviteView(LoginRequiredMixin, TemplateView):
    login_url = '/login/'
    template_name = 'invites.html'

    def get_context_data(self):
        context = super().get_context_data()
        context['user'] = str(self.request.user.pk)
        context['user_slug'] = self.request.user.personaname
        return context

templates/home.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>
 <head>
 <meta charset="UTF-8">
 <title>Example</title>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
 integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
 </head>

 <body>
     <a href="{% url "auth:logout" %}">Logout</a>
     <br>
     Hello, {{ user.personaname }}
     <div id="react" class="container"></div>

 {% render_bundle 'polyfill' %}
 {% render_bundle 'home' %}
 </body>
</html>

templates/index.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>
 <head>
 <meta charset="UTF-8">
 <title>Example</title>
 </head>

 <body>
 <div id="react"></div>
 {% if user.is_authenticated %}
     <a href="{% url "auth:logout" %}">Logout</a>
     <br>
     Hello, {{ user.personaname }}
 {% else %}
     <a href="{% url "social:begin" "steam" %}">Sign in with Steam</a>
 {% endif %}
 {% render_bundle 'main' %}
 </body>
</html>

templates/invites.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>
 <head>
 <meta charset="UTF-8">
 <title>Example</title>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
 integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
 </head>
 <script>
 window.props = {
    'user': '{{user}}',
    'user_slug': '{{user_slug}}',
 }
 </script>

 <body>
     <a href="{% url "auth:logout" %}">Logout</a>
     <br>
     Hello, {{ user.personaname }}
     <div id="react" class="container"></div>

 {% render_bundle 'polyfill' %}
 {% render_bundle 'invites' %}
 </body>
</html>

templates/login.html
<html>
 <head>
 <meta charset="UTF-8">
 <title>Login</title>
 </head>
 <body>
     <a href="{% url "social:begin" "steam" %}">Sign in with Steam</a>
 </body>
</html>

templates/players.html
{% load static %}
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>
 <head>
 <meta charset="UTF-8">
 <title>Example</title>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
 integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
 </head>

 <body>
     <a href="{% url "auth:logout" %}">Logout</a>
     <div id="players" class="container"></div>
 {% render_bundle 'polyfill' %}
 {% render_bundle 'players' %}
 <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
  integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
   integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
   integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
 </body>
</html>

templates/profile.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>
 <head>
 <meta charset="UTF-8">
 <title>Example</title>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
 integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
 </head>
 <script>
  window.props = {
    'user': '{{ user }}',
    'csrf_token':"{{ csrf_token }}",
  }
 </script>
 <body>
     <a href="{% url "auth:logout" %}">Logout</a>
     <div id="form" class="container" align="center"></div>
 {% render_bundle 'polyfill' %}
 {% render_bundle 'profile' %}
 <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
  integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
   integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
   integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
 </body>
</html>